# Generated by Django 5.1.3 on 2024-12-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Останній вхід"
            ),
        ),
    ]
