# Generated by Django 5.1.3 on 2025-01-10 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0004_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="booking.client",
            ),
        ),
    ]
