# Generated by Django 5.1.3 on 2025-01-11 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_promoparticipant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promoparticipant',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Учасник з таким Email вже зареєстрований. Спробуйте інший Email.'}, max_length=254, unique=True),
        ),
    ]
